name: socialoo
description: A new application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  video_player: ^2.2.3
 
  flutter_datetime_picker: ^1.4.0
  intl:
  image_cropper: ^1.5.1
  image_picker: ^0.6.2+1
  shared_preferences: ^0.5.12
  cached_network_image: ^2.5.0
  dio: ^3.0.10
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
  country_code_picker: ^1.6.2
  async: ^2.4.1
  toast: ^0.1.5
  flutter_absolute_path: 
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git
  path: ^1.7.0
  custom_refresh_indicator: ^0.8.0+1
  flutter_screenutil: ^0.4.2
  flutter_slidable: ^0.5.4
  giphy_get: ^1.1.0
  timeago: ^2.0.26
  inview_notifier_list: ^1.0.0
  path_provider: ^1.2.2
  image_gallery_saver: ^1.2.2
  permission_handler: ^5.0.1+1
  screenshot:
  dashed_circle: ^0.0.1
  google_fonts: ^1.1.1
  fluttertoast: ^7.1.8
  photofilters: ^1.0.5
  flutter_spinkit: ^4.1.2+1
  cloud_firestore: any
  firebase_auth: ^0.16.0
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.3
  firebase_messaging: ^6.0.16
  photo_view: ^0.9.2
  convex_bottom_bar: ^3.0.0
  another_flushbar: ^1.10.20
  google_sign_in: ^4.5.1
  csc_picker: ^0.2.5
  flutter_image_compress: ^0.7.0
  linkable: ^1.0.5
  flutter_staggered_grid_view: ^0.4.0
  webview_flutter: ^2.0.12
  visibility_detector: ^0.2.0
  video_thumbnail: ^0.4.3
  video_compress: ^3.0.0
  dynamic_themes:
  iconly: ^1.0.1
  nb_utils: ^3.3.0+13
  flutter_svg: ^0.19.3
  line_awesome_flutter: ^2.0.0
  adaptive_theme: ^1.1.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  ionicons: ^0.1.2
  share: ^2.0.4
  flutter_reaction_button: ^2.0.0+1
  google_mobile_ads: ^0.13.6
  filesize: ^2.0.1
  file_picker: ^2.1.7
  flutter_pdfview: ^1.2.2
  # geolocator: ^6.2.1
  geocoding: ^1.0.5

 

 
  
 


dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0   

flutter_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/video/


  fonts:
    
    - family: Helvetica  
      fonts:
        - asset: assets/fonts/Helvetica neue.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf 

    - family: BrushScript
      fonts:
        - asset: assets/fonts/brushScript.ttf  

    - family: icomoon
      fonts:
      - asset: assets/fonts/IcoMoon.ttf    

    - family: SpaceGrotesk
      fonts:
      - asset: assets/fonts/SpaceGrotesk-Bold.ttf 
